IF OBJECT_ID ( 'CountInfotypeAllFieldsData', 'P' ) IS NOT NULL   
    DROP PROCEDURE CountInfotypeAllFieldsData;  
GO
CREATE PROCEDURE [dbo].[CountInfotypeAllFieldsData]
AS
BEGIN
-- EXEC CountInfotypeAllFieldsData
-- SELECT * FROM WAVE_NM_INFOTYPE_COUNT ORDER BY TABLE_CATLOG, TABLE_NAME, COLUMN_NAME

	DELETE FROM WAVE_NM_INFOTYPE_COUNT
	INSERT INTO WAVE_NM_INFOTYPE_COUNT
	SELECT DISTINCT TABLE_CATALOG, SUBSTRING(TABLE_NAME, 4, LEN(TABLE_NAME)) TABLE_NAME, COLUMN_NAME, '0' COLUMN_COUNT
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME LIKE 'GV_%' AND 
			TABLE_CATALOG='Prod_DataClean';

	DECLARE @SQL              AS VARCHAR(4000)=''
	DECLARE @TABLE_CATALOG    AS VARCHAR(4000)=''
	DECLARE @TABLE_NAME       AS VARCHAR(4000)=''
	DECLARE @COLUMN_NAME      AS VARCHAR(4000)=''

	PRINT 'START';
	DECLARE cursor_item CURSOR FOR 
				   SELECT DISTINCT TABLE_CATALOG, SUBSTRING(TABLE_NAME, 4, LEN(TABLE_NAME)) TABLE_NAME, COLUMN_NAME
						FROM INFORMATION_SCHEMA.COLUMNS
						WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean'
	OPEN cursor_item;
	FETCH NEXT FROM cursor_item INTO @TABLE_CATALOG, @TABLE_NAME, @COLUMN_NAME;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT @TABLE_NAME+':'+@COLUMN_NAME
		SET @SQL='UPDATE WAVE_NM_INFOTYPE_COUNT 
					SET COLUMN_COUNT=ISNULL((SELECT COUNT(*) FROM GV_'+@TABLE_NAME+' WHERE ['+@COLUMN_NAME+'] IS NOT NULL), ''0'')
				  WHERE TABLE_NAME='''+@TABLE_NAME+''' AND COLUMN_NAME='''+@COLUMN_NAME+'''';
		EXEC(@SQL);

		FETCH NEXT FROM cursor_item INTO @TABLE_CATALOG, @TABLE_NAME, @COLUMN_NAME;
	END
	CLOSE cursor_item; 
	DEALLOCATE cursor_item;
	PRINT 'END'
END 
GO
