USE PROD_DATACLEAN
GO

IF OBJECT_ID ( 'PROC_WAVE_NM_AUTOMATE_INFOTYPE_CHANGES', 'P' ) IS NOT NULL   
    DROP PROCEDURE PROC_WAVE_NM_AUTOMATE_INFOTYPE_CHANGES;  
GO
CREATE PROCEDURE [dbo].[PROC_WAVE_NM_AUTOMATE_INFOTYPE_CHANGES]
    @which_table       AS VARCHAR(50),
	@which_field       AS VARCHAR(50),
	@which_flag        AS VARCHAR(50)
AS
BEGIN
    
	EXEC('
	WITH cte_pr AS (
		SELECT 
			'''+@which_field+''' FIELD,
			AEDTM,
			PERNR,
			'+@which_field+',
			SUBTY,
			LAG('+@which_field+',1) OVER (
				PARTITION BY PERNR
				ORDER BY AEDTM
			) PR_VALUE
		FROM 
			'+@which_table+' 
		WHERE
			ISNULL(SUBTY, '''') = '''+@which_subty+''' AND '+@which_field+' IS NOT NULL
	)
	INSERT INTO WAVE_NM_INFOTYPE_CHANGES
	SELECT 
		FIELD,
		AEDTM, 
		PERNR,
		SUBTY,
		'+@which_field+', 
		PR_VALUE,
		IIF(ISNULL('+@which_field+', '''')=ISNULL(PR_VALUE, ''''), ''No'', IIF(ISNULL(PR_VALUE, '''')='''', ''No'', ''Yes'')) VS_PR_VALUE
	FROM cte_pr
	WHERE '''+@which_flag+''' = ''No'' OR ('''+@which_flag+''' = ''Yes'' AND IIF(ISNULL('+@which_field+', '''')=ISNULL(PR_VALUE, ''''), ''No'', IIF(ISNULL(PR_VALUE, '''')='''', ''No'', ''Yes''))=''YES'')');
END
GO

IF OBJECT_ID ( 'PROC_WAVE_NM_AUTOMATE_ALL_INFOTYPE_CHANGES', 'P' ) IS NOT NULL   
    DROP PROCEDURE PROC_WAVE_NM_AUTOMATE_ALL_INFOTYPE_CHANGES;  
GO
CREATE PROCEDURE [dbo].[PROC_WAVE_NM_AUTOMATE_ALL_INFOTYPE_CHANGES]
	@which_flag        AS VARCHAR(50)
AS
BEGIN
--SELECT * FROM GV_PA2006

--EXEC PROC_WAVE_NM_AUTOMATE_INFOTYPE_CHANGES 'GV', 'PA0006', 'STRAS', '1', 'No'
--EXEC CheckInfotypeLatestCountry

/* Get All the table Column */

    --DROP TABLE WAVE_NM_INFOTYPE_CHANGES
	--GO
	--DECLARE @WAVE_NM_INFOTYPE_CHANGES TABLE (
	--    FIELD       VARCHAR(50),
	--	AEDTM       VARCHAR(50),
	--	PERNR       VARCHAR(50),		
	--	SUBTY       VARCHAR(50),		
	--	VALUE       NVARCHAR(2000),
	--	PR_VALUE    VARCHAR(2000),
	--    VS_PR_VALUE VARCHAR(100)
	--);
	--SELECT * INTO WAVE_NM_INFOTYPE_CHANGES FROM @WAVE_NM_INFOTYPE_CHANGES

    DELETE FROM WAVE_NM_INFOTYPE_CHANGES
	SELECT DISTINCT TABLE_CATALOG, TABLE_NAME, COLUMN_NAME
	   FROM INFORMATION_SCHEMA.COLUMNS
	   WHERE TABLE_NAME LIKE 'GV_%' AND 
			TABLE_CATALOG='Prod_DataClean' AND 
			--COLUMN_NAME NOT IN ('PERNR', 'BEGDA', 'ENDDA', 'SUBTY', 'AEDTM', 'MANDT') AND
			TABLE_CATALOG+TABLE_NAME NOT IN (


			/* Get All the tables without PERNR & SUBTY */
			SELECT TABLE_CATALOG+TABLE_NAME FROM (
			SELECT DISTINCT TABLE_CATALOG, TABLE_NAME
			   FROM INFORMATION_SCHEMA.COLUMNS
			   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND 
					 TABLE_NAME NOT IN (SELECT DISTINCT TABLE_NAME
										   FROM INFORMATION_SCHEMA.COLUMNS
										   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME='PERNR') 
			UNION ALL
			SELECT DISTINCT TABLE_CATALOG, TABLE_NAME
			   FROM INFORMATION_SCHEMA.COLUMNS
			   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND 
					 TABLE_NAME NOT IN (SELECT DISTINCT TABLE_NAME
										   FROM INFORMATION_SCHEMA.COLUMNS
										   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME='SUBTY')
			) A10
		)
		;

	EXEC PROC_WAVE_NM_AUTOMATE_INFOTYPE_CHANGES 'GV_PA0006', 'STRAS', '1', 'No';

	IF (@which_flag='Yes')
	BEGIN
	    SELECT * FROM WAVE_NM_INFOTYPE_CHANGES
	END

	SELECT CC, MAX(FIELD) FIELD, MAX(SUBTY) SUBTY, MAX(AEDTM) AEDTM, COUNT(*) [COUNTRIES_COUNT] FROM (
	     SELECT A1.*, A2.[geo - country (CC)] CC FROM WAVE_NM_INFOTYPE_CHANGES A1 
		    LEFT JOIN P0_POSITION_MANAGEMENT_BASE A2 ON A1.PERNR=A2.[emp - personnel number]
	) A3 
	GROUP BY CC


	SELECT DISTINCT TABLE_CATALOG, TABLE_NAME, COLUMN_NAME
	   FROM INFORMATION_SCHEMA.COLUMNS
	   WHERE TABLE_NAME LIKE 'GV_%' AND 
			TABLE_CATALOG='Prod_DataClean' AND 
			COLUMN_NAME NOT IN ('PERNR', 'BEGDA', 'ENDDA', 'SUBTY', 'AEDTM', 'MANDT') AND
			TABLE_CATALOG+TABLE_NAME NOT IN (


			/* Get All the tables without PERNR & SUBTY */
			SELECT TABLE_CATALOG+TABLE_NAME FROM (
			SELECT DISTINCT TABLE_CATALOG, TABLE_NAME
			   FROM INFORMATION_SCHEMA.COLUMNS
			   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND 
					 TABLE_NAME NOT IN (SELECT DISTINCT TABLE_NAME
										   FROM INFORMATION_SCHEMA.COLUMNS
										   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME='PERNR') 
			UNION ALL
			SELECT DISTINCT TABLE_CATALOG, TABLE_NAME
			   FROM INFORMATION_SCHEMA.COLUMNS
			   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND 
					 TABLE_NAME NOT IN (SELECT DISTINCT TABLE_NAME
										   FROM INFORMATION_SCHEMA.COLUMNS
										   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME='SUBTY')
			) A10
		);

END
GO


--/* Get All the tables */
--SELECT * FROM INFORMATION_SCHEMA.TABLES 

--/* Get All the table Column */
--SELECT DISTINCT TABLE_CATALOG, TABLE_NAME, COLUMN_NAME
--   FROM INFORMATION_SCHEMA.COLUMNS
--   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME NOT IN ('PERNR', 'BEGDA', 'ENDDA', 'SUBTY', 'AEDTM', 'MANDT')

--/* Get All the tables without PERNR & SUBTY */
--SELECT DISTINCT TABLE_CATALOG, TABLE_NAME
--   FROM INFORMATION_SCHEMA.COLUMNS
--   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND 
--         TABLE_NAME NOT IN (SELECT DISTINCT TABLE_NAME
--                               FROM INFORMATION_SCHEMA.COLUMNS
--                               WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME='PERNR') 
--UNION ALL
--SELECT DISTINCT TABLE_CATALOG, TABLE_NAME
--   FROM INFORMATION_SCHEMA.COLUMNS
--   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND 
--         TABLE_NAME NOT IN (SELECT DISTINCT TABLE_NAME
--                               FROM INFORMATION_SCHEMA.COLUMNS
--                               WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME='SUBTY')


--/* Get All the tables without SUBTY */
--SELECT DISTINCT TABLE_CATALOG, TABLE_NAME
--   FROM INFORMATION_SCHEMA.COLUMNS
--   WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND 
--         TABLE_NAME NOT IN (SELECT DISTINCT TABLE_NAME
--                               FROM INFORMATION_SCHEMA.COLUMNS
--                               WHERE TABLE_NAME LIKE 'GV_%' AND TABLE_CATALOG='Prod_DataClean' AND COLUMN_NAME='SUBTY')

--EXEC CheckInfotypeLatestCountry
--select "InfotypeCountryLatestDate"."Infotype",        "InfotypeCountryLatestDate"."InfotypeDescription",        "InfotypeCountryLatestDate"."Subty",        "InfotypeCountryLatestDate"."SubtyDescription",        "InfotypeCountryLatestDate"."Country",        "InfotypeCountryLatestDate"."ISO3",        "InfotypeCountryLatestDate"."LatestDate"   from "dbo"."InfotypeCountryLatestDate"        "InfotypeCountryLatestDate" order by "InfotypeCountryLatestDate"."Infotype"        asc
--SELECT * FROM InfotypeCountryLatestDate
--SELECT * FROM TempInfotypeCountries
--select * From CountInfotypeRecords
--SELECT * fROM P0_T042ZT